### ISSUE TITLE
Progress Tracking 

### ISSUE THREAD

**Issue by egoist** [freefolk/evergarden#1]
## Components

- [ ] Accordion
- [x] Alert
- [ ] AlertDialog
- [ ] Avatar
- [ ] Badge
- [x] Box
- [ ] Breadcrumb
- [x] Button
- [ ] Checkbox
- [ ] CloseButton
- [ ] Collapse
- [ ] Drawer
- [ ] Editable
- [ ] FormControl
- [ ] Heading
- [x] Icon
- [ ] IconButton
- [ ] Image
- [x] Input
- [x] InputGroup
- [x] InputElement
- [ ] InputAddon
- [ ] Link
- [ ] List
- [ ] Menu
- [ ] Modal *a lot of work*
- [ ] Popover *a lot of work*
- [ ] Progress
- [ ] Radio
- [ ] Slider
- [ ] Spinner
- [x] Stack
- [ ] Switch
- [ ] Tabs
- [ ] Tag
- [x] Text
- [ ] Textarea
- [ ] Toast *a lot of work*
- [ ] Tooltip *a lot of work*

## Docs

- [ ] Create a Saber theme
